[project]
name = "tgbot"
version = "0.1.0"
description = "Telegram bot with spaced repetition scheduling"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.22.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.6.0",
    "pydantic-settings>=2.0.3",
    "aiogram>=3.0.0b7",
    "httpx>=0.24.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
    "pytest-asyncio>=0.21"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
