name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Lint
        run: |
          pip install black isort
          black --check app tests
          isort --check-only app tests
      - name: Run tests
        env:
          TELEGRAM_BOT_TOKEN: dummy
          DATABASE_URL: sqlite:///./test.db
        run: |
          pytest -q
